# ===================================
#  Reorder Behavior Config
# ===================================

title: 'forwintercms.content::content.list.create_btn'
nameFrom: title
modelClass: ForWinterCms\Content\Models\Item
toolbar:
  buttons: reorder_toolbar