# ===================================
#  Form Behavior Config
# ===================================

name: "Content list"
modelClass: ForWinterCms\Content\Models\Item
form: $/forwintercms/content/models/item/fields.yaml

create:
  redirect: forwintercms/content/items/:page_slug/update/:id
  redirectClose: forwintercms/content/items/:page_slug
update:
  redirectClose: forwintercms/content/items/:page_slug
delete:
  redirectClose: forwintercms/content/items/:page_slug
preview: {}